package com.icmon.module.job.application.impl;

import com.icmon.module.job.application.interfaces.JobService;
import com.icmon.module.job.domain.TJob;
import com.icmon.module.job.domain.enums.JobStatus;
import com.icmon.module.job.infrastructure.cache.JobCacheService;
import com.icmon.module.job.infrastructure.cache.JobStatusCacheService;
import com.icmon.module.job.infrastructure.entity.JobEntity;
import com.icmon.module.job.infrastructure.entity.JobStatusHistoryEntity;
import com.icmon.module.job.infrastructure.mapper.JobMapper;
import com.icmon.module.job.infrastructure.repository.JobRepository;
import com.icmon.module.job.infrastructure.repository.JobStatusHistoryRepository;
import com.icmon.module.job.presentation.dto.request.JobCreateRequestDTO;
import com.icmon.module.job.presentation.dto.request.JobPartRequestDTO;
import com.icmon.module.job.presentation.dto.request.JobServiceRequestDTO;
import com.icmon.module.job.presentation.dto.request.JobStatusChangeRequestDTO;
import com.icmon.module.job.presentation.dto.request.JobUpdateRequestDTO;
import com.icmon.module.job.presentation.dto.response.JobDetailResponseDTO;
import com.icmon.module.job.presentation.dto.response.JobPartResponseDTO;
import com.icmon.module.job.presentation.dto.response.JobResponseDTO;
import com.icmon.module.job.presentation.dto.response.JobServiceResponseDTO;
import com.icmon.module.job.presentation.dto.response.JobStatusHistoryDTO;
import com.icmon.exception.SystemGlobalException;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class JobServiceImpl implements JobService {

    private final JobRepository jobRepository;
    private final JobStatusHistoryRepository jobStatusHistoryRepository;
    private final JobMapper jobMapper;
    private final JobCacheService jobCacheService;
    private final JobStatusCacheService jobStatusCacheService;

    /*
        ฟังก์ชันนี้สร้างใบงานใหม่ โดยรับข้อมูล DTO และบันทึกลงฐานข้อมูล พร้อมอัปเดต Cache
        This function creates a new job by receiving DTO data, saves to DB, and updates the cache.
    */
    @Override
    public JobResponseDTO createJob(JobCreateRequestDTO request) throws SystemGlobalException {
        // 1. แปลง DTO เป็น Entity / Convert DTO to Entity.
        JobEntity entity = new JobEntity();
        entity.setCustomerId(request.getCustomerId());
        entity.setCarId(request.getCarId());
        entity.setMechanicId(request.getMechanicId());
        entity.setStatus(JobStatus.OPEN);
        entity.setStartDate(LocalDateTime.now());
        entity.setSymptom(request.getSymptom());
        entity.setMileage(request.getMileage());
        entity.setPriority(request.getPriority() != null ? request.getPriority() : "NORMAL");
        entity.setDiagnosisNote(request.getDiagnosisNote());

        // 2. บันทึก (job_no จะถูกสร้างโดย DB Trigger) / Save (job_no is auto-generated by DB Trigger).
        JobEntity saved = jobRepository.save(entity);

        // 3. อัปเดต Cache / Update cache.
        TJob domain = jobMapper.toDomain(saved);
        jobCacheService.saveJob(domain);

        return toResponseDTO(saved);
    }

    @Override
    public JobResponseDTO getJob(UUID id) throws SystemGlobalException {
        JobEntity entity = jobRepository.findById(id)
                .orElseThrow(() -> new SystemGlobalException("Job not found: " + id, null));
        return toResponseDTO(entity);
    }

    @Override
    public JobDetailResponseDTO getJobDetail(UUID id) throws SystemGlobalException {
        JobEntity entity = jobRepository.findById(id)
                .orElseThrow(() -> new SystemGlobalException("Job not found: " + id, null));
        return JobDetailResponseDTO.builder()
                .id(entity.getId())
                .jobNo(entity.getJobNo())
                .customerId(entity.getCustomerId())
                .carId(entity.getCarId())
                .mechanicId(entity.getMechanicId())
                .status(entity.getStatus())
                .startDate(entity.getStartDate())
                .endDate(entity.getEndDate())
                .symptom(entity.getSymptom())
                .diagnosisNote(entity.getDiagnosisNote())
                .mileage(entity.getMileage())
                .estimatedCost(entity.getEstimatedCost())
                .actualCost(entity.getActualCost())
                .priority(entity.getPriority())
                .build();
    }

    @Override
    public Page<JobResponseDTO> listJobs(String status, String startDate, String endDate, Pageable pageable) throws SystemGlobalException {
        if (status != null) {
            JobStatus jobStatus = JobStatus.valueOf(status);
            return jobRepository.findByStatus(jobStatus, pageable).map(this::toResponseDTO);
        }
        return jobRepository.findAll(pageable).map(this::toResponseDTO);
    }

    @Override
    public JobResponseDTO updateJob(UUID id, JobUpdateRequestDTO request) throws SystemGlobalException {
        JobEntity entity = jobRepository.findById(id)
                .orElseThrow(() -> new SystemGlobalException("Job not found: " + id, null));

        if (request.getMechanicId() != null) entity.setMechanicId(request.getMechanicId());
        if (request.getSymptom() != null) entity.setSymptom(request.getSymptom());
        if (request.getDiagnosisNote() != null) entity.setDiagnosisNote(request.getDiagnosisNote());
        if (request.getMileage() != null) entity.setMileage(request.getMileage());
        if (request.getEstimatedCost() != null) entity.setEstimatedCost(request.getEstimatedCost());
        if (request.getPriority() != null) entity.setPriority(request.getPriority());

        JobEntity saved = jobRepository.save(entity);
        jobCacheService.evictJob(id);
        return toResponseDTO(saved);
    }

    @Override
    public JobResponseDTO changeStatus(UUID id, JobStatusChangeRequestDTO request) throws SystemGlobalException {
        JobEntity entity = jobRepository.findById(id)
                .orElseThrow(() -> new SystemGlobalException("Job not found: " + id, null));

        JobStatus oldStatus = entity.getStatus();
        if (oldStatus == JobStatus.CLOSED || oldStatus == JobStatus.CANCELLED) {
            throw new SystemGlobalException("Cannot change status of closed or cancelled job.", null);
        }

        entity.setStatus(request.getNewStatus());
        if (request.getNewStatus() == JobStatus.CLOSED || request.getNewStatus() == JobStatus.REPAIR_DONE) {
            entity.setEndDate(LocalDateTime.now());
        }

        JobEntity saved = jobRepository.save(entity);

        // บันทึก Status History / Record status history.
        JobStatusHistoryEntity history = new JobStatusHistoryEntity();
        history.setJobId(id);
        history.setFromStatus(oldStatus);
        history.setToStatus(request.getNewStatus());
        history.setChangedAt(LocalDateTime.now());
        history.setReason(request.getReason());
        history.setWhitelabelId(entity.getWhitelabelId());
        jobStatusHistoryRepository.save(history);

        jobCacheService.evictJob(id);
        jobStatusCacheService.evictJobStatus(id);

        return toResponseDTO(saved);
    }

    @Override
    public void deleteJob(UUID id) throws SystemGlobalException {
        jobRepository.findById(id)
                .orElseThrow(() -> new SystemGlobalException("Job not found: " + id, null));
        jobRepository.deleteById(id);
        jobCacheService.evictJob(id);
    }

    @Override
    public byte[] generateJobReport(UUID id) throws SystemGlobalException {
        // TODO: ใช้ JasperReports สร้าง PDF / Implement JasperReports PDF generation.
        throw new UnsupportedOperationException("Report generation not implemented yet");
    }

    @Override
    public List<JobStatusHistoryDTO> getStatusHistory(UUID id) throws SystemGlobalException {
        return jobStatusHistoryRepository.findByJobIdOrderByChangedAtAsc(id)
                .stream()
                .map(h -> JobStatusHistoryDTO.builder()
                        .id(h.getId())
                        .jobId(h.getJobId())
                        .fromStatus(h.getFromStatus())
                        .toStatus(h.getToStatus())
                        .changedBy(h.getChangedBy())
                        .changedAt(h.getChangedAt())
                        .reason(h.getReason())
                        .build())
                .collect(Collectors.toList());
    }

    @Override
    public JobServiceResponseDTO addService(UUID jobId, JobServiceRequestDTO request) throws SystemGlobalException {
        // TODO: เพิ่มรายการบริการให้กับใบงาน / Add service item to job.
        throw new UnsupportedOperationException("Not implemented yet");
    }

    @Override
    public JobPartResponseDTO addPart(UUID jobId, JobPartRequestDTO request) throws SystemGlobalException {
        // TODO: เพิ่มอะไหล่ให้กับใบงาน / Add part to job.
        throw new UnsupportedOperationException("Not implemented yet");
    }

    private JobResponseDTO toResponseDTO(JobEntity entity) {
        return JobResponseDTO.builder()
                .id(entity.getId())
                .jobNo(entity.getJobNo())
                .customerId(entity.getCustomerId())
                .carId(entity.getCarId())
                .mechanicId(entity.getMechanicId())
                .status(entity.getStatus())
                .startDate(entity.getStartDate())
                .endDate(entity.getEndDate())
                .symptom(entity.getSymptom())
                .diagnosisNote(entity.getDiagnosisNote())
                .mileage(entity.getMileage())
                .estimatedCost(entity.getEstimatedCost())
                .actualCost(entity.getActualCost())
                .priority(entity.getPriority())
                .build();
    }
}
