server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH}

spring:
  application:
    name: app-prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT:600000}
      max-lifetime: ${HIKARI_MAX_LIFETIME:1800000}
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:10}
      minimum-idle: ${HIKARI_MIN_IDLE:5}
      pool-name: HikariPool-1
      connection-test-query: SELECT 1
      auto-commit: true
      transaction-isolation: TRANSACTION_READ_COMMITTED

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA}

  data:
    mongodb:
      host: ${DATA_MONGODB_HOST}
      port: ${DATA_MONGODB_PORT}
      database: ${DATA_MONGODB_DATABASE}
      username: ${DATA_MONGODB_USERNAME}
      password: ${DATA_MONGODB_PASSWORD}
      authentication-database: ${DATA_MONGODB_AUTHENTICATION_DATABASE}

  neo4j:
    uri: ${DATA_NEO4J_URI}
    authentication:
      username: ${DATA_NEO4J_USER}
      password: ${DATA_NEO4J_PASSWORD}

jwt:
  publicKey: ${JWT_PUBLIC_KEY}
  privateKey: ${JWT_PRIVATE_KEY}